### ISSUE TITLE
command produces no result.

### ISSUE THREAD

**Issue by st33v** [rajatjindal/kubectl-whoami#7]
I'm using the AWS authenticator and I'm not able to get this comment to produce a username for me.

` 
❯ /usr/local/bin/kubectl-whoami --insecure-skip-tls-verify                                                                                                         
❯
`

I've tried the latest release from GitHub and the install vie Krew. Both produce the same result.

**Comment by rajatjindal** [comment]
Thank you for reporting the issue. Did it print any error message on the console?

**Comment by st33v** [comment]
nope... no output but has exit code == 0

`
❯ kubectl whoami
❯ echo $?
0
`

I CAN dump a user token and decode it using `whoami --token` but it seems like whom doesn't know how to handle aws's external authenticator.

**Comment by rajatjindal** [comment]
thanks for more details.

could you please provide more info about the cluster setup, so that I can try to reproduce the issue on my side:

I think following info will be useful, but please add any more info that you can provide:

- if possible, steps to reproduce on minikube cluster
- api server flags info for the RBAC (e.g. if you are using any oidc provider flags or `authentication-token-webhook-config-file`)
- version of kubernetes cluster

Thanks again

**Comment by rajatjindal** [comment]
I think i have some idea why this might be happening

Can u pls share your kubeconfig (with all sensitive data redacted)

Many thanks

**Comment by rajatjindal** [comment]
Hi (again) @st33v, long time :)

i have pushed a fix with version v0.0.36. could you please try the version and let me know if that fixes your issue.

sorry for all the delay.

**Comment by rajatjindal** [comment]
closing the issue as fixed. please feel free to reopen if that is not the case.
